package world

// Levels contains all level definitions.
// Each level is a 26x26 character grid.
// '.' = empty, 'B' = brick, 'S' = steel, 'W' = water,
// 'I' = ice, 'F' = forest, 'E' = eagle
//
// Key positions:
// - Player spawn: bottom centre (col 8-9, row 24-25)
// - Enemy spawns: top row at cols 0-1, 12-13, 24-25
// - Eagle: bottom centre (col 12-13, row 24-25)
var Levels = []string{
	// Level 1: Classic intro - mostly brick walls
	`.....BB..........BB.....
.....BB..........BB.....
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BB....BB..BB..
..BB..BB......SSBB..BB..
..BB..BB......SSBB..BB..
..........BB............
..........BB............
BB..BBBB..BB..BBBB..BB.
BB..BBBB......BBBB..BB.
..........BB............
..........BB............
..BB..BB......BB..BB..BB
..BB..BB......BB..BB..BB
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
..BB..BB..BB....BB..BB..
..........BB............
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 2: Steel fortress
	`..........................
..........................
..BB..SS..BBBB..SS..BB..
..BB..SS..BBBB..SS..BB..
..BB......BBBB......BB..
..BB......BBBB......BB..
......SS..BB..SS........
......SS......SS........
..BB......BB......BB....
..BB......BB......BB....
....SSBB..BB..BBSS......
....SSBB......BBSS......
..........SS............
..........SS............
....SSBB......BBSS......
....SSBB..BB..BBSS......
..BB......BB......BB....
..BB......BB......BB....
......SS......SS........
......SS..BB..SS........
..BB......BBBB......BB..
..BB......BBBB......BB..
..BB..SS..BBBB..SS..BB..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 3: Water maze
	`..........................
..........................
..BB..WW..BBBB..WW..BB..
..BB..WW..BBBB..WW..BB..
..BB..WW..BBBB..WW..BB..
..BB......BB........BB..
......BB..BB..BB........
......BB......BB........
..WW......BB......WW....
..WW......BB......WW....
....BBBB..BB..BBBB......
....BBBB......BBBB......
..WW......SS......WW....
..WW......SS......WW....
....BBBB......BBBB......
....BBBB..BB..BBBB......
..WW......BB......WW....
..WW......BB......WW....
......BB......BB........
......BB..BB..BB........
..BB......BBBB......BB..
..BB..WW..BBBB..WW..BB..
..BB..WW..BBBB..WW..BB..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 4: Forest ambush
	`..........................
..........................
..FF..BB..FFFF..BB..FF..
..FF..BB..FFFF..BB..FF..
..FF..BB..BBBB..BB..FF..
..FF......BBBB......FF..
..FF..BB..BB..BB..BB....
......BB......BB........
..BB..FF..BB..FF..BB....
..BB..FF..BB..FF..BB....
....FFBB..BB..BBFF......
....FFBB......BBFF......
..........BB............
..........BB............
....FFBB......BBFF......
....FFBB..BB..BBFF......
..BB..FF..BB..FF..BB....
..BB..FF..BB..FF..BB....
......BB......BB........
..FF..BB..BB..BB..BB....
..FF......BBBB......FF..
..FF..BB..BBBB..BB..FF..
..FF..BB..FFFF..BB..FF..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 5: Ice field
	`..........................
..........................
..II..BB..BBBB..BB..II..
..II..BB..BBBB..BB..II..
..II..BB..IIII..BB..II..
..II......IIII......II..
......BB..II..BB........
......BB......BB........
..BB..II..BB..II..BB....
..BB..II..BB..II..BB....
....IIBB..BB..BBII......
....IIBB......BBII......
..........SS............
..........SS............
....IIBB......BBII......
....IIBB..BB..BBII......
..BB..II..BB..II..BB....
..BB..II..BB..II..BB....
......BB......BB........
......BB..II..BB........
..II......IIII......II..
..II..BB..BBBB..BB..II..
..II..BB..BBBB..BB..II..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 6: Bunker assault
	`..........................
..........................
..SS..BB..SSSS..BB..SS..
..SS..BB..SSSS..BB..SS..
..BB..BB..BBBB..BB..BB..
..BB......BBBB......BB..
......SS..BB..SS........
......SS......SS........
..BB......BB......BB....
..BB......BB......BB....
..SSSSBB..BB..BBSSSS....
..SSSSBB......BBSSSS....
..........BB............
..........BB............
..SSSSBB......BBSSSS....
..SSSSBB..BB..BBSSSS....
..BB......BB......BB....
..BB......BB......BB....
......SS......SS........
......SS..BB..SS........
..BB......BBBB......BB..
..BB..BB..BBBB..BB..BB..
..SS..BB..SSSS..BB..SS..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 7: River crossing
	`..........................
..........................
..BB..BB..BBBB..BB..BB..
..BB..BB..BBBB..BB..BB..
WWWWWW....BBBB....WWWWWW
WWWWWW....BBBB....WWWWWW
..BB..BB..BB..BB..BB....
......BB......BB........
..BB......BB......BB....
..BB......BB......BB....
WWWWWWBB..BB..BBWWWWWW..
WWWWWWBB......BBWWWWWW..
..........BB............
..........BB............
WWWWWWBB......BBWWWWWW..
WWWWWWBB..BB..BBWWWWWW..
..BB......BB......BB....
..BB......BB......BB....
......BB......BB........
..BB..BB..BB..BB..BB....
WWWWWW....BBBB....WWWWWW
WWWWWW....BBBB....WWWWWW
..BB..BB..BBBB..BB..BB..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 8: Dense urban
	`..........................
..........................
..BBBB..BBBBBB..BBBB....
..BBBB..BBBBBB..BBBB....
..BB..BB..BBBB..BB..BB..
..BB......BB........BB..
..BBBB..BB..BB..BBBB....
......BB......BB........
..BB..BB..BB..BB..BB....
..BB..BB..BB..BB..BB....
..BBBBBB..BB..BBBBBB....
..BBBBBB......BBBBBB....
..........SS............
..........SS............
..BBBBBB......BBBBBB....
..BBBBBB..BB..BBBBBB....
..BB..BB..BB..BB..BB....
..BB..BB..BB..BB..BB....
......BB......BB........
..BBBB..BB..BB..BBBB....
..BB......BBBB......BB..
..BB..BB..BBBB..BB..BB..
..BBBB..BBBBBB..BBBB....
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 9: Mixed terrain gauntlet
	`..........................
..........................
..SS..WW..FFFF..WW..SS..
..SS..WW..FFFF..WW..SS..
..BB..II..BBBB..II..BB..
..BB......BBBB......BB..
..FF..SS..BB..SS..FF....
......BB......BB........
..WW..FF..BB..FF..WW....
..WW..FF..BB..FF..WW....
..IISSBB..BB..BBSSII....
..IISSBB......BBSSII....
..........SS............
..........SS............
..IISSBB......BBSSII....
..IISSBB..BB..BBSSII....
..WW..FF..BB..FF..WW....
..WW..FF..BB..FF..WW....
......BB......BB........
..FF..SS..BB..SS..FF....
..BB......BBBB......BB..
..BB..II..BBBB..II..BB..
..SS..WW..FFFF..WW..SS..
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,

	// Level 10: Final stand
	`..........................
..........................
SSSS..SS..SSSS..SS..SSSS
SSSS..SS..SSSS..SS..SSSS
..BB..BB..BBBB..BB..BB..
..BB......BBBB......BB..
..SS..SS..BB..SS..SS....
......SS......SS........
..BB..BB..SS..BB..BB....
..BB..BB..SS..BB..BB....
SSSSBBBB..SS..BBBBSSSS..
SSSSBBBB......BBBBSSSS..
..........SS............
..........SS............
SSSSBBBB......BBBBSSSS..
SSSSBBBB..SS..BBBBSSSS..
..BB..BB..SS..BB..BB....
..BB..BB..SS..BB..BB....
......SS......SS........
..SS..SS..BB..SS..SS....
..BB......BBBB......BB..
..BB..BB..BBBB..BB..BB..
SSSS..SS..SSSS..SS..SSSS
....BB....BBBB..BB......
....BB......BB..BB......
............EE..........`,
}
